// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttpqgfrulbkorwijtpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dHBxZ2ZydWxia29yd2lqdHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODIxNTQsImV4cCI6MjA2MjU1ODE1NH0.m55DARrCRwVDcosKJZUHqg-FNSCJs2S7j6OCihj5WA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);